from flask import Flask, render_template, request, jsonify, session, send_file
import os
from PIL import Image
import google.generativeai as genai
from dotenv import load_dotenv
from functools import wraps
import fitz  # PyMuPDF
from concurrent.futures import ThreadPoolExecutor
from concurrent.futures import TimeoutError as FutureTimeoutError
import pypandoc
import plotly.express as px
import plotly.utils
import pandas as pd
import base64
import io
from datetime import datetime
import hashlib
import sqlite3
import smtplib
import ssl
from html import escape
from email.message import EmailMessage
from werkzeug.security import check_password_hash, generate_password_hash

# Environment variables
load_dotenv()

app = Flask(__name__)
app.secret_key = os.urandom(24)
app.config['MAX_CONTENT_LENGTH'] = 16 * 1024 * 1024  # 16MB max file size
app.config['UPLOAD_FOLDER'] = 'uploads'
app.config['OUTPUT_FOLDER'] = 'outputs'
app.config['DATABASE'] = 'app.db'

# Create folders if they don't exist
os.makedirs(app.config['UPLOAD_FOLDER'], exist_ok=True)
os.makedirs(app.config['OUTPUT_FOLDER'], exist_ok=True)

def get_db_connection():
    """Create a SQLite connection with dict-like rows."""
    connection = sqlite3.connect(app.config['DATABASE'])
    connection.row_factory = sqlite3.Row
    return connection

def init_db():
    """Initialize the users table if it does not exist."""
    with get_db_connection() as connection:
        connection.execute(
            """
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                full_name TEXT NOT NULL,
                email TEXT NOT NULL UNIQUE,
                password_hash TEXT NOT NULL,
                created_at TEXT NOT NULL
            )
            """
        )
        connection.commit()

def get_current_user():
    """Return the logged-in user from the session."""
    user_id = session.get('user_id')
    if not user_id:
        return None

    with get_db_connection() as connection:
        row = connection.execute(
            "SELECT id, full_name, email, created_at FROM users WHERE id = ?",
            (user_id,)
        ).fetchone()

    return dict(row) if row else None

def login_required(route_function):
    """Require an authenticated session for API routes."""
    @wraps(route_function)
    def wrapper(*args, **kwargs):
        if not session.get('user_id'):
            return jsonify({'error': 'Please log in to continue'}), 401
        return route_function(*args, **kwargs)
    return wrapper

init_db()

# Maximum number of workers for the ThreadPoolExecutor
max_workers = 10
page_processing_timeout = 90

# Initialize model
google_api_key = os.getenv("GOOGLE_API_KEY")
if google_api_key:
    genai.configure(api_key=google_api_key)
    model = genai.GenerativeModel('gemma-3-27b-it')
else:
    model = None

# Functions
def get_gemini_response(input_text, image_data):
    """Get response from Gemini model"""
    if model is None:
        raise RuntimeError("GOOGLE_API_KEY is missing. Add it to your .env file and restart the app.")

    try:
        image_parts = [{"mime_type": "image/png", "data": image_data}]
        response = model.generate_content([input_text, image_parts[0]])
        if not getattr(response, "text", None):
            raise RuntimeError("The AI model returned an empty response.")
        return response.text
    except Exception as e:
        raise RuntimeError(f"AI processing failed: {str(e)}") from e

def pdf_to_images(pdf_file):
    """Convert PDF pages to images"""
    doc = fitz.open(stream=pdf_file.read(), filetype="pdf")
    images = []
    for page_num in range(len(doc)):
        page = doc.load_page(page_num)
        pix = page.get_pixmap(matrix=fitz.Matrix(300/72, 300/72))  # Higher resolution
        img_data = pix.tobytes("png")
        images.append({
            'page': page_num + 1,
            'data': base64.b64encode(img_data).decode('utf-8'),
            'raw_data': img_data
        })
    return images

def image_to_png_bytes(image_data):
    """Normalize uploaded images to PNG bytes for model input."""
    with Image.open(io.BytesIO(image_data)) as img:
        if img.mode not in ("RGB", "RGBA"):
            img = img.convert("RGB")

        buffer = io.BytesIO()
        img.save(buffer, format="PNG")
        return buffer.getvalue()

def md_to_latex(md_content):
    """Convert Markdown to LaTeX"""
    latex_preamble = r"""\documentclass[a4paper]{article}
\usepackage[utf8]{inputenc}
\usepackage{geometry}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{graphicx}
\usepackage{hyperref}
\geometry{margin=1in}
\title{Digitalized Notes}
\author{Generated by AI}
\date{\today}
\begin{document}
\maketitle
"""
    latex_body = pypandoc.convert_text(md_content, 'latex', format='md')
    return latex_preamble + latex_body + "\n\\end{document}"

def get_custom_prompt(format_type):
    """Get custom prompt based on format"""
    base_prompt = (
        "You are an expert at transcribing handwritten notes. Convert the handwritten text in this image "
        "into well-structured digital content. Maintain the original structure with headings, subheadings, "
        "paragraphs, and bullet points where applicable. Ensure mathematical equations are properly formatted. "
        "The output should be professional and ready for use."
    )
    
    format_prompts = {
        "Plain Text": f"{base_prompt} Output as clean plain text with proper spacing and indentation.",
        "Markdown": f"{base_prompt} Output in Markdown format with proper headers (#, ##, ###), lists, and formatting.",
        "LaTeX": f"{base_prompt} Output in LaTeX format with proper document structure and mathematical notation."
    }
    
    return format_prompts.get(format_type, base_prompt)

def translate_text_content(text, target_language):
    """Translate OCR output into the selected target language."""
    if model is None:
        raise RuntimeError("GOOGLE_API_KEY is missing. Add it to your .env file and restart the app.")

    if not text.strip():
        raise ValueError("No text provided for translation.")

    supported_languages = {
        'english': 'English',
        'hindi': 'Hindi',
        'tamil': 'Tamil',
        'telugu': 'Telugu',
        'malayalam': 'Malayalam'
    }

    normalized_language = target_language.strip().lower()
    language_name = supported_languages.get(normalized_language)
    if not language_name:
        raise ValueError("Unsupported language. Choose English, Hindi, Tamil, Telugu, or Malayalam.")

    translation_prompt = (
        f"Translate the following OCR output into {language_name}. "
        "Preserve the original structure, paragraphs, headings, bullet points, and formatting style. "
        "Return only the translated text without explanations.\n\n"
        f"OCR Output:\n{text}"
    )

    try:
        response = model.generate_content(translation_prompt)
        if not getattr(response, "text", None):
            raise RuntimeError("The AI model returned an empty translation.")
        return {
            'language_key': normalized_language,
            'language_name': language_name,
            'translated_text': response.text
        }
    except Exception as e:
        raise RuntimeError(f"Translation failed: {str(e)}") from e

def answer_document_question(document_text, question, language_label='Original OCR', chat_history=None):
    """Answer user questions using only the provided converted document."""
    if model is None:
        raise RuntimeError("GOOGLE_API_KEY is missing. Add it to your .env file and restart the app.")

    if not document_text.strip():
        raise ValueError("No converted document text is available for analysis.")

    if not question.strip():
        raise ValueError("Please enter a question for the document assistant.")

    history_lines = []
    for item in (chat_history or [])[-6:]:
        role = (item.get('role') or '').strip().lower()
        content = (item.get('content') or '').strip()
        if role in {'user', 'assistant'} and content:
            speaker = 'User' if role == 'user' else 'Assistant'
            history_lines.append(f"{speaker}: {content}")

    history_block = '\n'.join(history_lines) if history_lines else 'No previous conversation.'

    prompt = (
        "You are NeuralNotes Document Assistant.\n"
        "Answer the user's question using only the information found in the converted document text.\n"
        "If the document does not contain the answer, clearly say that the answer is not available in the document.\n"
        "Do not invent facts, page numbers, or references.\n"
        "Keep the response helpful, direct, and easy to understand.\n"
        "If the user asks for a summary, explanation, key points, definitions, or extracted facts, provide them only from the document.\n\n"
        f"Current document view: {language_label}\n\n"
        f"Conversation so far:\n{history_block}\n\n"
        f"Converted document text:\n{document_text}\n\n"
        f"User question:\n{question}"
    )

    try:
        response = model.generate_content(prompt)
        if not getattr(response, "text", None):
            raise RuntimeError("The AI model returned an empty answer.")
        return response.text.strip()
    except Exception as e:
        raise RuntimeError(f"Document chat failed: {str(e)}") from e

def send_document_email(
    recipient_email,
    subject,
    body,
    attachment_name,
    attachment_content,
    format_type='Plain Text',
    language_label='Original OCR',
    custom_message=''
):
    """Send the converted document as an email attachment."""
    smtp_host = os.getenv('SMTP_HOST')
    smtp_port = int(os.getenv('SMTP_PORT', '587'))
    smtp_user = os.getenv('SMTP_USER') or os.getenv('SMTP_USERNAME')
    smtp_password = os.getenv('SMTP_PASSWORD')
    from_email = os.getenv('FROM_EMAIL') or os.getenv('MAIL_FROM') or smtp_user
    smtp_use_tls = os.getenv('SMTP_USE_TLS', 'true').lower() != 'false'

    missing_settings = []
    if not smtp_host:
        missing_settings.append('SMTP_HOST')
    if not from_email:
        missing_settings.append('FROM_EMAIL or MAIL_FROM')

    if missing_settings:
        raise RuntimeError(
            "Email is not configured. Missing: "
            + ", ".join(missing_settings)
            + ". Supported variables: SMTP_HOST, SMTP_PORT, SMTP_USER or SMTP_USERNAME, SMTP_PASSWORD, FROM_EMAIL or MAIL_FROM."
        )

    message = EmailMessage()
    message['From'] = from_email
    message['To'] = recipient_email
    message['Subject'] = subject
    message.set_content(body)
    message.add_alternative(
        build_document_email_html(
            subject=subject,
            format_type=format_type,
            language_label=language_label,
            attachment_name=attachment_name,
            custom_message=custom_message,
            document_text=attachment_content
        ),
        subtype='html'
    )
    message.add_attachment(
        attachment_content.encode('utf-8'),
        maintype='text',
        subtype='plain',
        filename=attachment_name
    )

    context = ssl.create_default_context()
    with smtplib.SMTP(smtp_host, smtp_port, timeout=30) as server:
        if smtp_use_tls:
            server.starttls(context=context)
        if smtp_user and smtp_password:
            server.login(smtp_user, smtp_password)
        server.send_message(message)

def build_document_email_html(subject, format_type, language_label, attachment_name, custom_message, document_text):
    """Build a responsive HTML email for document delivery."""
    preview_text = document_text.strip().replace('\r\n', '\n')
    preview_text = '\n'.join(line.strip() for line in preview_text.split('\n') if line.strip())
    preview_text = preview_text[:420] + ('...' if len(preview_text) > 420 else '')
    preview_html = escape(preview_text or 'Your document is attached and ready to review.').replace('\n', '<br>')
    custom_message_html = ''

    if custom_message:
        custom_message_html = f"""
            <tr>
              <td style="padding:0 32px 24px 32px;">
                <div style="background:linear-gradient(135deg,#fff7ed 0%,#ffedd5 100%); border:1px solid #fed7aa; border-radius:20px; padding:20px 22px;">
                  <div style="font-size:12px; letter-spacing:0.14em; text-transform:uppercase; color:#c2410c; font-weight:700; margin-bottom:10px;">Sender Message</div>
                  <div style="font-size:15px; line-height:1.7; color:#7c2d12;">{escape(custom_message).replace(chr(10), '<br>')}</div>
                </div>
              </td>
            </tr>
        """

    return f"""\
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{escape(subject)}</title>
  </head>
  <body style="margin:0; padding:0; background-color:#eef2ff; font-family:Segoe UI, Arial, sans-serif; color:#0f172a;">
    <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:
      radial-gradient(circle at top left, #dbeafe 0%, #eef2ff 38%, #f8fafc 100%);
      margin:0;
      padding:24px 12px;">
      <tr>
        <td align="center">
          <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:680px; background:#ffffff; border-radius:28px; overflow:hidden; box-shadow:0 22px 70px rgba(15,23,42,0.16);">
            <tr>
              <td style="padding:0;">
                <div style="background:linear-gradient(135deg,#0f172a 0%,#1d4ed8 52%,#22c55e 100%); padding:40px 32px 120px 32px; position:relative;">
                  <div style="display:inline-block; background:rgba(255,255,255,0.16); color:#e0f2fe; border:1px solid rgba(255,255,255,0.24); border-radius:999px; padding:8px 14px; font-size:12px; font-weight:700; letter-spacing:0.08em; text-transform:uppercase;">
                    NeuralNotes Delivery Studio
                  </div>
                  <div style="margin-top:18px; font-size:32px; line-height:1.2; font-weight:800; color:#ffffff;">
                    Your document is ready in real time.
                  </div>
                  <div style="margin-top:14px; max-width:520px; font-size:16px; line-height:1.7; color:rgba(255,255,255,0.84);">
                    A converted NeuralNotes file has just been shared with you. Open the attachment to continue reviewing, editing, or forwarding the latest output.
                  </div>
                </div>
              </td>
            </tr>
            <tr>
              <td style="padding:0 32px;">
                <div style="margin-top:-78px; background:rgba(255,255,255,0.96); border:1px solid rgba(148,163,184,0.18); border-radius:24px; box-shadow:0 18px 40px rgba(15,23,42,0.10); padding:24px;">
                  <table role="presentation" width="100%" cellspacing="0" cellpadding="0">
                    <tr>
                      <td style="padding:0 0 14px 0; font-size:13px; font-weight:700; letter-spacing:0.12em; text-transform:uppercase; color:#64748b;">
                        Delivery Details
                      </td>
                    </tr>
                  </table>
                  <table role="presentation" width="100%" cellspacing="0" cellpadding="0">
                    <tr>
                      <td width="50%" style="padding:0 8px 12px 0; vertical-align:top;">
                        <div style="background:#f8fafc; border:1px solid #e2e8f0; border-radius:18px; padding:16px;">
                          <div style="font-size:12px; color:#64748b; text-transform:uppercase; letter-spacing:0.08em; font-weight:700;">Format</div>
                          <div style="margin-top:8px; font-size:20px; color:#0f172a; font-weight:800;">{escape(format_type)}</div>
                        </div>
                      </td>
                      <td width="50%" style="padding:0 0 12px 8px; vertical-align:top;">
                        <div style="background:#f8fafc; border:1px solid #e2e8f0; border-radius:18px; padding:16px;">
                          <div style="font-size:12px; color:#64748b; text-transform:uppercase; letter-spacing:0.08em; font-weight:700;">Language View</div>
                          <div style="margin-top:8px; font-size:20px; color:#0f172a; font-weight:800;">{escape(language_label)}</div>
                        </div>
                      </td>
                    </tr>
                    <tr>
                      <td colspan="2" style="padding:0;">
                        <div style="background:#f8fafc; border:1px solid #e2e8f0; border-radius:18px; padding:16px;">
                          <div style="font-size:12px; color:#64748b; text-transform:uppercase; letter-spacing:0.08em; font-weight:700;">Attachment</div>
                          <div style="margin-top:8px; font-size:18px; color:#0f172a; font-weight:700; word-break:break-word;">{escape(attachment_name)}</div>
                        </div>
                      </td>
                    </tr>
                  </table>
                </div>
              </td>
            </tr>
            {custom_message_html}
            <tr>
              <td style="padding:28px 32px 18px 32px;">
                <div style="font-size:14px; font-weight:700; color:#1e293b; margin-bottom:12px;">Document preview</div>
                <div style="background:#0f172a; border-radius:22px; padding:22px; color:#dbeafe; font-size:14px; line-height:1.75; box-shadow:inset 0 0 0 1px rgba(148,163,184,0.18);">
                  {preview_html}
                </div>
              </td>
            </tr>
            <tr>
              <td style="padding:0 32px 32px 32px;">
                <div style="background:linear-gradient(135deg,#eff6ff 0%,#f8fafc 100%); border:1px solid #dbeafe; border-radius:20px; padding:18px 20px; font-size:14px; line-height:1.7; color:#334155;">
                  This email includes the converted document as an attachment so you can open it directly in your preferred editor or archive it for later.
                </div>
              </td>
            </tr>
            <tr>
              <td style="padding:0 32px 32px 32px;">
                <div style="border-top:1px solid #e2e8f0; padding-top:18px; font-size:12px; line-height:1.8; color:#64748b;">
                  Sent by NeuralNotes AI on behalf of a signed-in workspace user.<br>
                  This is an automated delivery from the document sharing flow.
                </div>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </body>
</html>
"""

def generate_character_frequency(text):
    """Generate character frequency analysis"""
    frequency = {}
    total_chars = len(text)
    
    for char in text:
        if char.isalnum() or char.isspace():
            frequency[char] = frequency.get(char, 0) + 1
    
    df = pd.DataFrame(list(frequency.items()), columns=['Character', 'Frequency'])
    df['Percentage'] = (df['Frequency'] / total_chars * 100).round(2)
    return df.sort_values(by='Frequency', ascending=False).head(20)

def generate_word_frequency(text):
    """Generate word frequency analysis"""
    words = text.lower().split()
    word_freq = {}
    stop_words = {'the', 'a', 'an', 'and', 'or', 'but', 'in', 'on', 'at', 'to', 'for', 'of', 'with', 'by'}
    
    for word in words:
        word = word.strip('.,!?;:()[]{}')
        if word and word not in stop_words and len(word) > 2:
            word_freq[word] = word_freq.get(word, 0) + 1
    
    df = pd.DataFrame(list(word_freq.items()), columns=['Word', 'Frequency'])
    return df.sort_values(by='Frequency', ascending=False).head(15)

def generate_document_stats(text):
    """Generate document statistics"""
    words = text.split()
    sentences = text.count('.') + text.count('!') + text.count('?')
    paragraphs = text.count('\n\n') + 1
    
    return {
        'total_characters': len(text),
        'total_words': len(words),
        'total_sentences': sentences,
        'total_paragraphs': paragraphs,
        'avg_word_length': round(len(text) / len(words), 2) if words else 0,
        'avg_sentence_length': round(len(words) / sentences, 2) if sentences else 0
    }

def process_file_async(file_data, filename, format_type, session_id):
    """Process uploaded PDF or image file asynchronously."""
    temp_path = None
    try:
        file_ext = os.path.splitext(filename)[1].lower()

        if file_ext == '.pdf':
            temp_path = os.path.join(app.config['UPLOAD_FOLDER'], f"{session_id}.pdf")
            with open(temp_path, 'wb') as f:
                f.write(file_data)

            with open(temp_path, 'rb') as f:
                images = pdf_to_images(io.BytesIO(f.read()))
        elif file_ext in {'.png', '.jpg', '.jpeg'}:
            images = [{
                'page': 1,
                'raw_data': image_to_png_bytes(file_data)
            }]
        else:
            raise ValueError("Unsupported file type. Please upload a PDF, PNG, JPG, or JPEG file.")
        
        # Process each page
        tasks = []
        worker_count = max(1, min(max_workers, len(images), 3))
        with ThreadPoolExecutor(max_workers=worker_count) as executor:
            for img in images:
                prompt = get_custom_prompt(format_type)
                tasks.append((img['page'], executor.submit(get_gemini_response, prompt, img['raw_data'])))
        
        # Combine results
        page_results = []
        for page_num, task in tasks:
            try:
                page_results.append((page_num, task.result(timeout=page_processing_timeout)))
            except FutureTimeoutError as e:
                raise TimeoutError(
                    f"Processing timed out on page {page_num}. Please try a smaller or clearer file."
                ) from e

        output_text = "\n\n--- Page Break ---\n\n".join(
            result for _, result in sorted(page_results, key=lambda item: item[0])
        )
        
        # Post-process based on format
        if format_type == "LaTeX":
            output_text = md_to_latex(output_text)
        
        # Save output
        output_ext = {
            "Plain Text": "txt",
            "Markdown": "md",
            "LaTeX": "tex"
        }.get(format_type, "txt")
        
        output_path = os.path.join(app.config['OUTPUT_FOLDER'], f"{session_id}.{output_ext}")
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(output_text)
        
        # Generate analytics
        char_freq = generate_character_frequency(output_text)
        word_freq = generate_word_frequency(output_text)
        doc_stats = generate_document_stats(output_text)
        
        return {
            'success': True,
            'output': output_text,
            'output_path': output_path,
            'analytics': {
                'character_frequency': char_freq.to_dict('records'),
                'word_frequency': word_freq.to_dict('records'),
                'document_stats': doc_stats,
                'total_pages': len(images)
            }
        }
    except Exception as e:
        return {'success': False, 'error': str(e)}
    finally:
        # Cleanup
        if temp_path and os.path.exists(temp_path):
            os.remove(temp_path)

@app.route('/')
def index():
    """Main page"""
    return render_template('index.html', current_user=get_current_user())

@app.route('/api/auth/status')
def auth_status():
    """Return the current authentication state."""
    user = get_current_user()
    return jsonify({
        'authenticated': bool(user),
        'user': user
    })

@app.route('/api/auth/signup', methods=['POST'])
def signup():
    """Create a new user account."""
    data = request.get_json(silent=True) or {}
    full_name = data.get('full_name', '').strip()
    email = data.get('email', '').strip().lower()
    password = data.get('password', '')

    if len(full_name) < 2:
        return jsonify({'error': 'Please enter your full name'}), 400
    if '@' not in email or '.' not in email:
        return jsonify({'error': 'Please enter a valid email address'}), 400
    if len(password) < 8:
        return jsonify({'error': 'Password must be at least 8 characters long'}), 400

    try:
        with get_db_connection() as connection:
            cursor = connection.execute(
                """
                INSERT INTO users (full_name, email, password_hash, created_at)
                VALUES (?, ?, ?, ?)
                """,
                (full_name, email, generate_password_hash(password), datetime.now().isoformat())
            )
            connection.commit()
            user_id = cursor.lastrowid
    except sqlite3.IntegrityError:
        return jsonify({'error': 'An account with this email already exists'}), 409

    session['user_id'] = user_id
    return jsonify({
        'success': True,
        'message': 'Account created successfully',
        'user': get_current_user()
    })

@app.route('/api/auth/login', methods=['POST'])
def login():
    """Authenticate an existing user."""
    data = request.get_json(silent=True) or {}
    email = data.get('email', '').strip().lower()
    password = data.get('password', '')

    if not email or not password:
        return jsonify({'error': 'Email and password are required'}), 400

    with get_db_connection() as connection:
        user = connection.execute(
            "SELECT id, full_name, email, password_hash, created_at FROM users WHERE email = ?",
            (email,)
        ).fetchone()

    if not user or not check_password_hash(user['password_hash'], password):
        return jsonify({'error': 'Invalid email or password'}), 401

    session['user_id'] = user['id']
    return jsonify({
        'success': True,
        'message': 'Logged in successfully',
        'user': get_current_user()
    })

@app.route('/api/auth/logout', methods=['POST'])
def logout():
    """Log out the current user."""
    session.pop('user_id', None)
    return jsonify({
        'success': True,
        'message': 'Logged out successfully'
    })

@app.route('/api/upload', methods=['POST'])
@login_required
def upload_file():
    """Handle file upload and processing"""
    if 'file' not in request.files:
        return jsonify({'error': 'No file uploaded'}), 400
    
    file = request.files['file']
    format_type = request.form.get('format', 'Plain Text')
    
    if file.filename == '':
        return jsonify({'error': 'No file selected'}), 400
    
    allowed_extensions = {'.pdf', '.png', '.jpg', '.jpeg'}
    file_ext = os.path.splitext(file.filename)[1].lower()

    if file_ext not in allowed_extensions:
        return jsonify({'error': 'Only PDF, PNG, JPG, and JPEG files are allowed'}), 400
    
    try:
        # Generate unique session ID
        session_id = hashlib.md5(f"{datetime.now().timestamp()}{file.filename}".encode()).hexdigest()
        
        # Read file data
        file_data = file.read()
        
        # Process file
        result = process_file_async(file_data, file.filename, format_type, session_id)
        
        if result['success']:
            # Store in session
            session['last_output'] = result['output']
            session['last_format'] = format_type
            session['last_analytics'] = result['analytics']
            
            return jsonify({
                'success': True,
                'output': result['output'],
                'analytics': result['analytics'],
                'session_id': session_id
            })
        else:
            return jsonify({'error': result['error']}), 500
            
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/download/<session_id>')
@login_required
def download_file(session_id):
    """Download processed file"""
    format_type = request.args.get('format', 'Plain Text')
    
    ext_map = {
        'Plain Text': 'txt',
        'Markdown': 'md',
        'LaTeX': 'tex'
    }
    
    filename_map = {
        'Plain Text': 'converted_notes.txt',
        'Markdown': 'converted_notes.md',
        'LaTeX': 'converted_notes.tex'
    }
    
    mime_map = {
        'Plain Text': 'text/plain',
        'Markdown': 'text/markdown',
        'LaTeX': 'application/x-tex'
    }
    
    file_path = os.path.join(app.config['OUTPUT_FOLDER'], f"{session_id}.{ext_map.get(format_type, 'txt')}")
    
    if os.path.exists(file_path):
        return send_file(
            file_path,
            as_attachment=True,
            download_name=filename_map.get(format_type, 'converted_notes.txt'),
            mimetype=mime_map.get(format_type, 'text/plain')
        )
    else:
        return jsonify({'error': 'File not found'}), 404

@app.route('/api/analytics', methods=['POST'])
@login_required
def generate_analytics():
    """Generate analytics for text"""
    data = request.json
    text = data.get('text', '')
    
    if not text:
        return jsonify({'error': 'No text provided'}), 400
    
    char_freq = generate_character_frequency(text)
    word_freq = generate_word_frequency(text)
    doc_stats = generate_document_stats(text)
    
    return jsonify({
        'character_frequency': char_freq.to_dict('records'),
        'word_frequency': word_freq.to_dict('records'),
        'document_stats': doc_stats
    })

@app.route('/api/translate', methods=['POST'])
@login_required
def translate_output():
    """Translate extracted OCR output into a supported language."""
    data = request.get_json(silent=True) or {}
    text = data.get('text', '')
    target_language = data.get('target_language', '')

    if not text.strip():
        return jsonify({'error': 'No text provided for translation'}), 400

    if not target_language:
        return jsonify({'error': 'No target language selected'}), 400

    try:
        result = translate_text_content(text, target_language)
        translated_text = result['translated_text']

        return jsonify({
            'success': True,
            'target_language': result['language_key'],
            'target_language_name': result['language_name'],
            'translated_text': translated_text,
            'analytics': {
                'character_frequency': generate_character_frequency(translated_text).to_dict('records'),
                'word_frequency': generate_word_frequency(translated_text).to_dict('records'),
                'document_stats': generate_document_stats(translated_text)
            }
        })
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/document-chat', methods=['POST'])
@login_required
def document_chat():
    """Answer questions about the converted document."""
    data = request.get_json(silent=True) or {}
    document_text = data.get('document_text', '')
    question = data.get('question', '')
    language_label = data.get('language_label', 'Original OCR')
    chat_history = data.get('chat_history', [])

    if not document_text.strip():
        return jsonify({'error': 'Run OCR prediction before using the document assistant'}), 400

    if not question.strip():
        return jsonify({'error': 'Please enter a question'}), 400

    try:
        answer = answer_document_question(
            document_text=document_text,
            question=question,
            language_label=language_label,
            chat_history=chat_history
        )
        return jsonify({
            'success': True,
            'answer': answer
        })
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/share/email', methods=['POST'])
@login_required
def share_via_email():
    """Send the current converted document to an email address."""
    data = request.get_json(silent=True) or {}
    recipient_email = data.get('recipient_email', '').strip()
    document_text = data.get('document_text', '')
    format_type = data.get('format_type', 'Plain Text')
    language_label = data.get('language_label', 'Original OCR')
    source_filename = data.get('source_filename', 'converted_document')
    custom_message = data.get('message', '').strip()

    if '@' not in recipient_email or '.' not in recipient_email:
        return jsonify({'error': 'Please enter a valid recipient email address'}), 400

    if not document_text.strip():
        return jsonify({'error': 'No converted document content was provided'}), 400

    extension = {
        'Plain Text': 'txt',
        'Markdown': 'md',
        'LaTeX': 'tex'
    }.get(format_type, 'txt')

    safe_base_name = os.path.splitext(source_filename)[0] or 'converted_document'
    attachment_name = f"{safe_base_name}_{language_label.replace(' ', '_').lower()}.{extension}"
    subject = f"NeuralNotes Document - {language_label}"
    body = (
        "Your converted NeuralNotes document is attached.\n\n"
        f"Format: {format_type}\n"
        f"Language view: {language_label}\n"
    )
    if custom_message:
        body += f"\nMessage from sender:\n{custom_message}\n"

    try:
        send_document_email(
            recipient_email=recipient_email,
            subject=subject,
            body=body,
            attachment_name=attachment_name,
            attachment_content=document_text,
            format_type=format_type,
            language_label=language_label,
            custom_message=custom_message
        )
        return jsonify({
            'success': True,
            'message': f'Document sent to {recipient_email}'
        })
    except Exception as e:
        return jsonify({'error': str(e)}), 500

if __name__ == '__main__':
    init_db()
    app.run(debug=True, host='0.0.0.0', port=5000)
